# Generated by Django 5.2.8 on 2025-11-06 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse_mac', models.CharField(max_length=50, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdresseIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('attribuee', 'Attribuée')], default='disponible', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipmanager.device')),
            ],
        ),
    ]
