# Generated by Django 5.2.8 on 2025-11-08 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ordinateur', 'Ordinateur'), ('imprimante', 'Imprimante'), ('serveur', 'Serveur'), ('camera', 'Caméra'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('adresse_mac', models.CharField(max_length=50, unique=True)),
                ('actif', models.BooleanField(default=False)),
                ('derniere_detection', models.DateTimeField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SousReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cidr', models.CharField(max_length=50)),
                ('passerelle', models.CharField(blank=True, max_length=50, null=True)),
                ('dns', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdresseIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('attribuee', 'Attribuée'), ('reservee', 'Réservée')], default='disponible', max_length=20)),
                ('actif', models.BooleanField(default=False)),
                ('derniere_detection', models.DateTimeField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipmanager.device')),
                ('sous_reseau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipmanager.sousreseau')),
            ],
        ),
    ]
