# Generated by Django 5.2.8 on 2025-11-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sousreseau',
            old_name='cidr',
            new_name='plage_ip',
        ),
        migrations.AddField(
            model_name='sousreseau',
            name='total_adresses',
            field=models.IntegerField(default=254),
        ),
        migrations.AlterField(
            model_name='sousreseau',
            name='dns',
            field=models.CharField(default='8.8.8.8', max_length=50),
        ),
        migrations.AlterField(
            model_name='sousreseau',
            name='passerelle',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
    ]
