# Generated by Django 5.2.8 on 2025-11-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresseip',
            name='actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adresseip',
            name='derniere_detection',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
